config/routes.rb
Rails.application.routes.draw do
  resources :places
  resources :searches

  devise_for :users
  root 'homes#show'
  
  
end

app/models/place.rb
class Place < ActiveRecord::Base
	#attr_accessor :bedrooms, :description, :place_images, :max_occupancy, :property_type, :title, :address_attributes, :month_price, :check_in, :check_out, :special_info
    #attr_accessor :place_images_attributes
    belongs_to :user  
    
    has_many :place_images, dependent: :destroy 
    validates_associated :place_images
    accepts_nested_attributes_for :place_images

    def self.search(search)
    	if search
    		where(["city LIKE ? OR country LIKE ?", "%#{search}%", "%#{search}%"])
    	else
    		all
    	end
    end

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  
  before_action :authenticate_user!, except: [:index ]
  before_action :find_place, only: [:show, :destroy, :update, :edit]
  
  def index
    @places = Place.search(params[:search]).order("created_at DESC")
  end

  def new
    @place = Place.new
    
  end

  def create
    @place = current_user.places.build(place_params)
      
    respond_to do |format|  
      if @place.save
        if params[:photos]
        
          params[:photos].each { |photo|
            @place.place_images.create(photo: photo)
          }
        end
        format.html { redirect_to @place, notice: 'Flat was successfully created.' }
        format.json { render json: @place, status: :created, location: @place }
      else
        flash[:messages] ||= []
        flash[:messages] << @place.errors.full_messages
        render 'new'
      end
    end  
  end

  def show
    #@place = Place.includes(:owner).find(params[:id])
  end

  def destroy
    
    @place.destroy

    redirect_to root_path
  end

  def edit
    
  end

  def update
    respond_to do |format|
      if @place.update_attributes(place_params)
        if params[:photos]
          # The magic is here ;)
          params[:photos].each { |image|
            @place.pictures.create(photo: image)
          }
        end
        format.html { redirect_to @place, notice: 'Gallery was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  private 
    def place_params
      params.require(:place).permit(:title, :description, :property_type, :max_occupancy, :bedrooms, :place_images, :city, :state, :zip, :country, :month_price, :special_info )
    end

    def find_place
      @place = Place.find(params[:id])

    end

end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.erb
<div class= "container">
  <div class="col-md-4, col-md-offset-2">
    <div id="box1" class="boxed blurred-bg tinted">
      <div class="content">
        <h1>Rent you Flat</h1>

        <hr>
        <%= form_for @place, html: { multipart: true } do |f| %>
          <div>
            <% @place.errors.full_messages.each do |error| %>
              <li><%= error %></li>
            <% end %>
          </div>
          <div id="about_your_place" class="new_form_box">

            <label for="title">Title</label><br>
            <input type="text" id="title" name="place[title]" value="<%= @place.title %>" class="form-control">
            <br>

            <label for="description">Description</label><br>
            <textarea id="description>" name="place[description]" class="form-control">
              <%= @place.description %>
            </textarea>
            <br>

            <label for="property_type">Property Type</label>
            <% property_type_array = ("apartment, house, cabin, villa castle, dorm, treehouse, boat, plane, van, camper, igloo, lighthouse, yurt, tipi, cave, island, chalet, earth-house, hut, tent, other").split(", ") %>
            <select id="property_type" 
                    name="place[property_type]" 
                    class="selectpicker select-block">
              <% property_type_array.each do |prp| %>
                <option value="<%= prp %>" <%= 'selected' if @place.property_type == prp %>>
                  <%= prp.capitalize %>
                </option>
              <% end %>
            </select>
            <br>

            <label for="accommodates">Accommodates</label>
            <select id="accommodates" 
                    name="place[max_occupancy]" 
                    class="selectpicker select-block">
              <% 15.times do |num| %>
                <option value="<%= num+1 %>" <%= 'selected' if @place.max_occupancy == '#{num+1}' %>>
                    <%= num+1 %>
                </option>
              <% end %>
              <option value="16">16+</option>
            </select>
            <br>

           
            <label for="bedrooms">Bedrooms</label>
            <select id="bedrooms" 
                    name="place[bedrooms]" 
                    class="selectpicker select-block">
              <% 10.times do |num| %>
                <option value="<%= num+1 %>"<%= 'selected' if @place.bedrooms == '#{num+1}'%>>
                  <%= num+1 %>
                </option>
              <% end %>
            </select>
            <br>
          </div>

            <label for="country">Country</label>
            <input type="text" 
                   id="country" 
                   name="place[country]"
                   value="<%= @place.country %>" class="form-control">   
            <br>

           

            <label for="city">City</label>
            <input type="text" 
                   id="city" 
                   name="place[city]"
                   value="<%= @place.city %>" class="form-control">   
            <br>

            <label for="state">State</label>
            <input type="text" 
                   id="state" 
                   name="place[state]"
                   value="<%= @place.state %>" class="form-control">   
            <br>

            <label for="zip">Zip Code</label>
            <input type="text" 
                   id="zip" 
                   name="place[zip]"
                   value="<%= @place.zip %>" class="form-control"> 
            <br>      
           
          

          <div id="rental_options" class="new_form_box">
            
            <label for="month_price">Price Per Month</label><br>
            <input type="text"
                   id="month_price"
                   name="place[month_price]"
                   value="<%= @place.month_price %>" class="form-control">
                   <br>

            

            <label for="special_info">Any Special Instructions?</label><br>
            <textarea id="special_info" name="place[special_info]" class="form-control">
              <%= @place.special_info %>
            </textarea>
            <br>
          </div>
          <br>
            <p>
              
              <%= file_field_tag "photos[]", multiple: true , type: :file, class: "form-control" %>
            </p>
          <br>
          <input id="submit_listing" type="submit" value="Create Listing" class="btn btn-primary float_left">
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/places/edit.html.erb
<h1>Places#edit</h1>
<p>Find me in app/views/places/edit.html.erb</p>

app/views/places/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Rent your flat</title>
  
  
	<style type="text/css">
  header{
    position: fixed;
    top:0;
    left: 0;  
    width: 100%;
    height: 60px;
    background: #4a5f70;

    box-shadow: 0 0 15px #000 ;
  }

  #logoCont{
    background: #000;
    width: 150px;
    height: 50px;
    float: left;
    margin: 5px 0 0 50px;
  }

  #searchBox{
    float: left;
    margin: 8px 0 0 30px; 
    background: #5e717f;

    background: -webkit-linear-gradient(left, #5e717f , #4a5f70); /* For Safari 5.1 to 6.0 */
    background: -o-linear-gradient(left, #5e717f, #4a5f70); /* For Opera 11.1 to 12.0 */
    background: -moz-linear-gradient(left, #5e717f, #4a5f70); /* For Firefox 3.6 to 15 */
    background: linear-gradient(left, #5e717f , #4a5f70); /* Standard syntax */
  }
  #searchBox input{
    border: none;
    height: 35px;
    width: 610px;
    color:#fff;
    outline: none;
    padding: 5px 15px ;
    border-radius: 7px;
    background: none;
    font-size: 30px;

    border-radius: 5px;
  }
  #salutation{
    float: left;
    margin: 20px 50px 0 0;
    color: #000;
    font-size: 25px;
  }

  #salutation ul{
    margin:0 0 20px 50px;
  }

  a{
    text-decoration: none;
    color:#fff;
  }
  a:hover{
    font-weight: bold;
    text-decoration: none;
  }
  #map {
    height: 85%;
    width: 40%;
    position: relative;
    float: right;
    margin: 5px 10px 0 0; 
    border-radius: 0 7px 0 0;
  }

#type-selector {
  color: #fff;
  background-color: #4d90fe;
  padding: 5px 11px 0px 11px;
}

#type-selector label {
  font-family: Roboto;
  font-size: 13px;
  font-weight: 300;
}

::-webkit-input-placeholder {
   color: #fff;
}

:-moz-placeholder { /* Firefox 18- */
   color: #fff;  
}

::-moz-placeholder {  /* Firefox 19+ */
   color: #fff;  
}

:-ms-input-placeholder {  
   color: #fff;  
}

#dashboard{
  width: 100%;
  height: 100%;
  top:65px;
  position: fixed;
  background: #ebf2f6;
  left: 0;
  word-wrap: break-word;
}
#flatSearched{
  width: 58%;
  height: 85%;
  float: left;
  position: absolute;
  overflow-y: scroll;

  margin: 5px 0 0 10px;
  border-radius: 7px 0 0 0;
  background: #f7f6f4;
}

.flatBox{
  background: #aaa;
  width: 45%;
  height: 250px;
  position: relative;
  float: left;
  border-radius: 7px 7px 0 0;
  cursor: pointer;
  margin:15px 0 10px 20px;
}
.flatBox:hover{
  box-shadow: 0 0 15px 1px #000;
}

.container {
  position: relative;
}
#clip {
  position: absolute;
  clip: rect(0, 100px, 200px, 0);
  /* clip: shape(top, right, bottom, left); NB 'rect' is the only available option */
}

footer {
  position: fixed;
  bottom: -10px; 
  color: #000;
  width: 100%;
}

footer a{
  font-size: 17px;
  color: #000;
  text-decoration: none !important;
}

ul{
  list-style: none;
  color: #233e54;
}

ul li{
  display: inline;
}


	</style>
</head>
<body>
	<div id="container">
		<header>
			
			<div id="logoCont">
			<%= link_to "LOGO", root_path %>
			</div>
			
			<div id="searchBox">
          
          		<input id="pac-input" class="controls" type="text" placeholder="Search for flats on rent ">
			</div>
			<div id="salutation">

		        <ul> 
		            <a href="#"><li>Rent Your Flat</li></a> | 
		            <a href="#"><li>Hello <%= current_user.name if user_signed_in? %></li></a>
		        </ul>
			</div>
		</header>

	    <div id="dashboard">
	    	<div>
        
	    	  <%= link_to "Advanced Search", new_search_path, class: "btn btn-danger btn-lg" %>
	    	</div>
		    <div id="flatSearched">
          <% if @places.empty? %>
            <h1>Sorry! No results found.</h1>
          <% else %>  
  			    <% @places.each do |place| %>
  			        <div class="flatBox">
                  <div>
                    <% if place.place_images.first %>
                      <p><%= link_to image_tag(place.place_images.first.photo.url(:thumb)), place_path(place) %></p>
                    <% end %>  
    			        </div>
                  <div>
                    <p style="text-align: center;">
                      <p><%= place.title %></p>
                      <p><%= place.description.truncate(14) %></p>
                      <p><%= link_to "Show", place_path(place) %>
                      <%= link_to "Edit", edit_place_path(place) %>
                      <%= link_to "Delete", place, data: { confirm: "Are you sure?" },method: :delete
                      %></p>
                    </p>
                  </div>
                </div>  
  			    <% end %>
          <% end %>    
		    </div>
	      <div id="map" style=""></div>
	    </div>

  	</div>
    <footer>
      <ul>
        <li>&copy; Rented.com | </li>
        <li><a href="#">About Us</a> | </li> 
        <li><a href="#">Contact Us</a> | </li> 
        <li><a href="#">Terms &amp; Conditions</a> | </li> 
      </ul>
    </footer>
	 <script>

	function initAutocomplete() {

		function _(inp) {
			return document.getElementById(inp);
		}
		  var map = new google.maps.Map(_('map'), {
		    center: {lat: 21, lng: 82},
		    zoom: 4,
		    mapTypeId: google.maps.MapTypeId.ROADMAP
		  });

		  // Create the search box and link it to the UI element.
		  var input = _('pac-input');
		  var searchBox = new google.maps.places.SearchBox(input);
		  //map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);

		  // Bias the SearchBox results towards current map's viewport.
		  map.addListener('bounds_changed', function() {
		    searchBox.setBounds(map.getBounds());
		  });

		  var markers = [];
		  // [START region_getplaces]
		  // Listen for the event fired when the user selects a prediction and retrieve
		  // more details for that place.
		  searchBox.addListener('places_changed', function() {
		    var places = searchBox.getPlaces();

		    if (places.length == 0) {
		      return;
		    }

		    // Clear out the old markers.
		    markers.forEach(function(marker) {
		      marker.setMap(null);
		    });
		    markers = [];

		    // For each place, get the icon, name and location.
		    var bounds = new google.maps.LatLngBounds();
		    places.forEach(function(place) {
		      var icon = {
		        url: place.icon,
		        size: new google.maps.Size(71, 71),
		        origin: new google.maps.Point(0, 0),
		        anchor: new google.maps.Point(17, 34),
		        scaledSize: new google.maps.Size(25, 25)
		      };

		      // Create a marker for each place.
		      markers.push(new google.maps.Marker({
		        map: map,
		        icon: icon,
		        title: place.name,
		        position: place.geometry.location
		      }));

		      if (place.geometry.viewport) {
		        // Only geocodes have viewport.
		        bounds.union(place.geometry.viewport);
		      } else {
		        bounds.extend(place.geometry.location);
		      }
		    });
		    map.fitBounds(bounds);
		  });
		  // [END region_getplaces]
		}
	</script>
	<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDusQAmGtEwiKnZ1QQfJI4gLaivOwhv0QA&libraries=places&callback=initAutocomplete"
         async defer></script>
</body>
</html>

app/views/places/new.html.haml
.container
	=render 'form'

app/views/places/show.html.erb
<h1><%= @place.title %></h1>

<div id="tabs" class="tabs_box">
  <ul class="height_adjust">
    <li><a href="#tabs-1">Photo</a></li>
    <li><a href="#tabs-2">Place Details</a></li>
    <li><a href="#tabs-3">Rental Details</a></li>
    <li><a href="#tabs-4">Address Info</a></li>
  </ul>
  <div id="tabs-1">
    <div class="main_photo">
      <% @place.place_images.each do |p| %>
      	<%= image_tag p.photo.url %>
      <% end %>	
    </div>

  </div>
  <div id="tabs-2">
    <div id="description">
      <p><b>Descripton:</b> <br><%= @place.description %></p>
    </div>

    <div class="show_details show">
      <ul id="show_details">
        <li><b>Accommodates:</b> <%= @place.max_occupancy %></li>
        <li><b>Bedrooms:</b> <%= @place.bedrooms %></li>
      </ul>
    </div>
  </div>

  <div id="tabs-3">
    <div class="show_rental_details show">
      
      <h4>Special Instructions:</h4>
      <p class="center_me"><%= @place.special_info %></p>
    </div>
  </div>

  <div id="tabs-4">
    <div class="show_address show clear_me">
      <ul id="address">
        <li><b>Address:</b> 
        <li><b>City:</b> <%= @place.city %></li>  
        <li><b>State:</b> <%= @place.state %></li>
        <li><b>Zip Code:</b> <%= @place.zip %></li>
      </ul>
    </div>
  </div>
</div>





  